<?php
require_once(realpath(dirname(__FILE__).'/../SeleniumTests.php'));
class product1 extends SeleniumTests
{
  public function testMyTestCase()
  {
	//Авторизация в аккаунте
	$this->login();
	print("upd14" . "\n");
    print("-----------------------------------------Авторизуюсь как админ" . "\n");
    $this->open("http://jcstage.co/access/logout/");
    $this->open("http://jcstage.co/access/logon/");
    $this->type("id=user_name-input", "admin");
    $this->type("id=password-input", "1qaz2wsx");
    $this->click("css=input[type=\"submit\"]");
    $this->waitForPageToLoad("30000");
	print("-----------------------------------------Авторизовался как админ" . "\n");
	//Конец авторизации
   // Создаю переменные неолбходимые для теста
    print("Создаю переменные для теста" . "\n");
    $cifr = $this->getEval("\"zifr01\"+Math.random().toString(36).substring(8)");
    $fiz = $this->getEval("\"fizich01\"+Math.random().toString(36).substring(8)");
    $plav = $this->getEval("\"plav01\"+Math.random().toString(36).substring(8)");
    $skidka50proc = $this->getEval("\"skidka50proc\"+Math.random().toString(36).substring(8)");
    $tag1 = $this->getEval("\"tag1\"+Math.random().toString(36).substring(8)");
    $tag2 = $this->getEval("Math.floor(Math.random()*1111111)");
    $testpage = $this->getEval("\"testpage\"+Math.random().toString(36).substring(8)");
    $testpage2 = $this->getEval("\"testpage\"+Math.random().toString(36).substring(8)");
    $name = $this->getEval("\"name\"+Math.random().toString(36).substring(8)");
    $mail = $this->getEval("\"mail\"+Math.random().toString(36).substring(8)+\"@\"+Math.random().toString(36).substring(8)+\".ru\"");
    $phone = $this->getEval("Math.floor(Math.random()*1111111)");
    // Создание категорий
	print("Создаю категории" . "\n");
    $this->open("/shops/groups/");
    $this->click("//span[@class=\"in\"][text()=\"+ Добавить\"]");
    $this->waitForPageToLoad("30000");
    $this->click("name=group_title");
    $this->type("name=group_title", $cifr);
    $this->click("name=save");
    $this->waitForPageToLoad("30000");
    $this->click("//span[@class=\"in\"][text()=\"+ Добавить\"]");
    $this->waitForPageToLoad("30000");
    $this->click("name=group_title");
    $this->type("name=group_title", $fiz);
    $this->click("name=save");
    $this->waitForPageToLoad("30000");
    $this->click("//span[@class=\"in\"][text()=\"+ Добавить\"]");
    $this->waitForPageToLoad("30000");
    $this->click("name=group_title");
    $this->type("name=group_title", $plav);
    $this->click("name=save");
    $this->waitForPageToLoad("30000");
    sleep(5);
    // Создание продуктов
	print("Приступаю к созданию продукта" . "\n");
	print("Открываю страницу shops/goods" . "\n");
    $this->open("/shops/goods/");
	sleep(5);
    $this->click("css=a.button.mid > span.in");
	print("Кликнул по кнопке Добавить" . "\n");
    $this->waitForPageToLoad("30000");
    $this->type("name=good_name", $cifr);
	print("Ввел идентификатор" . "\n");
    $this->click("name=good_title");
    $this->type("name=good_title", "продуктцифровой");
	print("Ввел название" . "\n");
    $this->type("name=good_sum", "5000");
	print("Ввел сумму" . "\n");
    $this->click("css=span.rightSelectCorner");
    $this->click("link=" . $cifr);
	print("Выбрал категорию продктов" . "\n");
    $this->click("css=#partnership > tbody > tr.acordeon-tit > td > div.toolbar > a > i.icon-showed");
	print("Раскрыл вкладку Партнерство" . "\n");
    $this->type("name=good_partner_fee_perc", "50");
    $this->type("name=good_partner_fee", "50");
    $this->type("name=good_partner_pfee_perc[]", "20");
    $this->type("name=good_partner_pfee[]", "20");
    $this->click("name=save");
	print("Сохранил продукт" . "\n");
    $this->waitForPageToLoad("30000");
    sleep(5);
    $this->click("css=a.button.mid > span.in");
    $this->waitForPageToLoad("30000");
    $this->click("id=good_type-1");
    $this->click("css=span.rightSelectCorner");
    $this->click("link=" . $fiz);
    $this->type("name=good_name", $fiz);
    $this->click("name=good_title");
    $this->type("name=good_title", "продуктфизический");
    $this->type("name=good_sum", "4000");
    $this->click("name=good_publish");
    $this->click("name=save");
    $this->waitForPageToLoad("30000");
    $this->click("css=a.button.mid > span.in");
    $this->waitForPageToLoad("30000");
    $this->click("id=good_type-2");
    $this->click("css=span.rightSelectCorner");
    $this->click("link=" . $plav);
    $this->click("name=good_name");
    $this->type("name=good_name", $plav);
    $this->type("name=good_title", "продуктплавающий");
    $this->type("name=good_sum", "3000");
    $this->click("name=save");
    $this->waitForPageToLoad("30000");
    sleep(3);
    // Проверка создания клиентских групп
	print("Проверяю создались ли клиентские группы" . "\n");
    $this->click("link=Группы контактов");
    $this->waitForPageToLoad("30000");
    $this->click("css=span.in.cw110");
    $this->type("name=filter[kw]", $cifr);
    $this->click("link=Искать");
    sleep(5);
    $this->assertTrue($this->isElementPresent("//td[@class=\"textleft\"]/b[text()=\"clients_" . $cifr . "\"]"));
    $this->click("css=span.in.cw110");
    $this->type("name=filter[kw]", $fiz);
    $this->click("link=Искать");
    sleep(5);
    $this->assertTrue($this->isElementPresent("//td[@class=\"textleft\"]/b[text()=\"clients_" . $fiz . "\"]"));
    $this->click("css=span.in.cw110");
    $this->type("name=filter[kw]", $plav);
    $this->click("link=Искать");
    sleep(5);
    $this->assertTrue($this->isElementPresent("//td[@class=\"textleft\"]/b[text()=\"clients_" . $plav . "\"]"));
    // Проверка ссылок
	print("Проверяю основные ссылки в меню" . "\n");
    $this->click("link=Категории");
    $this->waitForPageToLoad("30000");
    $this->click("link=Продукты");
    $this->waitForPageToLoad("30000");
    $this->click("link=Скидки");
    $this->waitForPageToLoad("30000");
    $this->click("link=Соавторы");
    $this->waitForPageToLoad("30000");
    $this->click("link=Генератор кнопки");
    $this->waitForPageToLoad("30000");
    $this->click("link=Генератор формы");
    $this->waitForPageToLoad("30000");
    $this->click("link=Продукты");
    $this->waitForPageToLoad("30000");
    $this->click("css=span.in.cw110");
    $this->click("name=filter[kw]");
    $this->type("name=filter[kw]", $cifr);
    $this->click("link=Искать");
    sleep(2);
    // Допродажа, чистая прибыль, скидка
	print("Допродажа, чистая прибыль , скидка" . "\n");
    $this->click("//article[@id='main-view']/div[6]/div/table/tbody/tr[2]/td[7]/a");
    $this->waitForPageToLoad("30000");
    $this->verifyTextPresent("В данный момент допродажа отключена (включить).");
    $this->click("//article[@id='main-view']/div[3]/div/a");
    sleep(2);
    $this->verifyTextPresent("В данный момент допродажа включена (отключить).");
    $this->click("link=Продукты");
    $this->waitForPageToLoad("30000");
    $this->click("//article[@id='main-view']/div[6]/div/div/p/a/i");
    $this->waitForPageToLoad("30000");
    $this->click("name=save");
    $this->waitForPageToLoad("30000");
    $this->click("css=a.count-report");
    $this->waitForPageToLoad("30000");
    $this->click("//article[@id='main-view']/div[6]/a/span[2]");
    $this->waitForPageToLoad("30000");
    // Настройка допродажи
	print("Настраиваю допрожажу" . "\n");
    $this->click("//article[@id='main-view']/div[6]/div/table/tbody/tr[2]/td[7]/a");
    $this->waitForPageToLoad("30000");
    $this->click("//td[2]/a/span[2]");
    $this->click("css=span.rightSelectCorner");
    $this->click("link=" . $fiz . "| продуктфизический");
    $this->click("name=good_sum");
    $this->type("name=good_sum", "2000");
    $this->click("css=div.form-value > span.button.mid > span.in > input[name=\"save\"]");
    sleep(7);
    $this->click("name=save");
    $this->waitForPageToLoad("30000");
    $this->click("css=i.icon-sort-down");
    $this->click("css=i.icon-sort-down");
    $this->click("css=i.icon-dotted");
    $this->waitForPageToLoad("30000");
    sleep(2);
    $this->click("name=save");
    $this->waitForPageToLoad("30000");
    $this->click("//article[@id='main-view']/div[5]/div/div/div/a/span[2]");
    sleep(7);
    $this->click("//td[2]/a/span[2]");
    $this->click("css=span.rightSelectCorner");
    $this->click("link=" . $plav . "| продуктплавающий");
    $this->click("name=good_sum");
    $this->type("name=good_sum", "1000");
    $this->click("css=div.form-value > span.button.mid > span.in > input[name=\"save\"]");
    sleep(7);
    $this->type("name=good_partner_fee_perc", "010");
    $this->type("name=good_partner_pfee_perc[]", "05");
    sleep(5);
    $this->click("name=save");
    $this->waitForPageToLoad("30000");
    $this->click("//article[@id='main-view']/div[7]/a/span[2]");
    $this->waitForPageToLoad("30000");
    // Создание скидки
	print("Создаю скидку" . "\n");
    $this->open("/shops/discount/");
    sleep(5);
    $this->click("//a[2]/span[2]");
    $this->waitForPageToLoad("30000");
    $this->type("name=discount_kupon", $skidka50proc);
    $this->type("name=discount_title", "skidka50percent");
    $this->type("name=discount_value", "50");
    $this->click("name=good[all]");
    $this->click("name=save");
    $this->waitForPageToLoad("30000");
    sleep(5);
    // Создание формы заказа
	print("Создаю форму заказа" . "\n");
    $this->open("/shops/bills/formcode/");
    $this->click("//label[text()=' " . $cifr . "']/input");
    $this->click("//label[text()=' " . $fiz . "']/input");
    $this->click("//label[text()=' " . $plav . "']/input");
	print("Выбрал продукты" . "\n");
    $this->click("//table[3]/tbody/tr/td/div/a/i");
    $this->sendKeys("id=form-kupon", $skidka50proc);
    $this->sendKeys("id=code-tag", $tag1);
	print("Ввел скидку, маркер, ввожу логин партнера партнера" . "\n");
    $this->type("id=code-aff", "jcgreg");
    $this->keyDown("id=code-aff", "w");
    $this->keyPress("id=code-aff", "w");
    $this->keyUp("id=code-aff", "w");
    for ($second = 0; ; $second++) {
        if ($second >= 60) $this->fail("timeout");
        try {
            if ($this->isElementPresent("//a[@class=\"ui-corner-all\"][text()=\"jcgreg\"]")) break;
        } catch (Exception $e) {}
        sleep(1);
    }

    $this->click("//a[@class=\"ui-corner-all\"][text()=\"jcgreg\"]");
	print("Жму на всплывший логин партнера" . "\n");
    $this->click("css=i.icon-showed");
    $this->click("id=code-show-kupon");
    $this->click("//textarea[@id='code-result']");
    $this->runScript("GetFormCode();");
    $cod = $this->getValue("id=code-result");
    // Вставка кода на страницу
	print("Создаю страницу и вставляю код" . "\n");
    $this->click("link=Страницы");
    $this->waitForPageToLoad("30000");
    sleep(2);
	print("Кликнул по линку Страницы" . "\n");
    $this->click("link=Основной сайт");
    $this->waitForPageToLoad("30000");
    sleep(5);
	print("Кликнул по линку Основной сайт" . "\n");
    $this->click("css=a.button.mid > span.in");
    $this->waitForPageToLoad("30000");
	print("Кликнул по кнопке Добавить" . "\n");
    $this->type("name=content_name", $testpage);
	print("Ввел идентификатор страницы" . "\n");
    $this->type("name=variant_title[0]", $testpage);
	print("Ввел название страницы" . "\n");
    sleep(1);
	print("*************************************" . "\n");
    print($cod . "\n");
    $str = join('\n', split("\n", $cod)); // заменяем перенос строки на символ переноса строки
	print("str=".$str. "\n");
    $str = join("\'", split("'", $str)); // ставим перед одинарной кавычкой обратный слешь
	print("str=".$str. "\n");
    $this->runScript("CKEDITOR.instances['variant_html[0]'].setData('" . $str . "');");
    sleep(1);
	print("3" . "\n");
    $this->click("name=save");
    $this->waitForPageToLoad("30000");
    sleep(5);
    // Оформление заказа
	print("Оформляю заказ" . "\n");
    $this->open("/" . $testpage . "/");
    $this->click("id=good-name-" . $cifr);
    $this->type("name=bill_first_name", $name);
    $this->type("name=bill_email", $mail);
    $this->type("name=bill_phone", $phone);
    $this->click("//nobr/span");
    $this->waitForPageToLoad("30000");
    $this->click("xpath=(//input[@value='Нет, спасибо'])[2]");
    $this->waitForPageToLoad("30000");
    $this->assertTrue($this->isElementPresent("//h3[text()=\"На сумму:  2 500 руб.\"]"));
    $this->open("/shops/bills/");
    $this->click("css=span.in.cw110");
    sleep(0.5);
    $this->click("name=col-marker");
    $this->click("name=col-partners");
    $this->click("//input[@value='Применить']");
    $this->assertTrue($this->isElementPresent("//td[@class=\"col-marker td-left\"][text()=\"" . $tag1 . "\"]"));
    $this->assertTrue($this->isElementPresent("//td[@class=\"col-partners td-right\"]/div[text()=\"jcgreg\"]"));
    // Создание кнопки заказа
    print("Создание кнопки заказа" . "\n");
    $this->open("/shops/bills/button/");
    $this->click("xpath=(//label[text()=' " . $cifr . "']/input)");
    $this->click("xpath=(//label[text()=' " . $fiz . "']/input)");
    $this->click("xpath=(//label[text()=' " . $plav . "']/input)");
    $this->click("//table[3]/tbody/tr/td/div/a/i");
    $this->sendKeys("id=code-kupon", $skidka50proc);
    $this->sendKeys("id=code-tag", $tag2);
	print("Ввел скидку, маркер, ввожу логин партнера партнера" . "\n");
    $this->type("id=code-aff", "testbranch");
    $this->keyDown("id=code-aff", "w");
    $this->keyPress("id=code-aff", "w");
    $this->keyUp("id=code-aff", "w");
    for ($second = 0; ; $second++) {
        if ($second >= 60) $this->fail("timeout");
        try {
            if ($this->isElementPresent("//a[@class=\"ui-corner-all\"][text()=\"testbranch\"]")) break;
        } catch (Exception $e) {}
        sleep(1);
    }

    $this->click("//a[@class=\"ui-corner-all\"][text()=\"testbranch\"]");
	print("Жму на всплывший логин партнера" . "\n");
    sleep(5);
    $this->click("//textarea[@id='code-result']");
    $this->runScript("GetFormCode();");
    $js = $this->getValue("id=code-result");
    // Ухожу создавать страницу для кнопки заказа
    print("Ухожу создавать страницу для кнопки заказа" . "\n");
    sleep(1);
    $this->click("link=Страницы");
    $this->waitForPageToLoad("30000");
    sleep(2);
    $this->click("link=Основной сайт");
    $this->waitForPageToLoad("30000");
    $this->click("css=a.button.mid > span.in");
    $this->waitForPageToLoad("30000");
    sleep(5);
    $this->type("name=content_name", $testpage2);
    $this->type("name=variant_title[0]", $testpage2);
    sleep(1);
    $str = join('\n', split("\n", $js)); // заменяем перенос строки на символ переноса строки
    $str = join("\'", split("'", $str)); // ставим перед одинарной кавычкой обратный слешь
    $this->runScript("CKEDITOR.instances['variant_html[0]'].setData('" . $str . "');");
    sleep(1);
    $this->click("name=save");
    $this->waitForPageToLoad("30000");
    sleep(5);
    // Оформление заказа
	print("Оформляю заказ на странице с кнопкой" . "\n");
    $this->open("/" . $testpage2);
    $this->click("//span");
    $this->waitForPageToLoad("30000");
    sleep(5);
    $this->click("id=good-name-" . $plav);
    $this->type("name=bill_first_name", $name);
    $this->type("name=bill_email", $mail);
    $this->type("name=bill_phone", $phone);
    $this->click("//tr[14]/td/input");
    $this->waitForPageToLoad("30000");
    $this->assertTrue($this->isElementPresent("//h3[text()=\"На сумму:  1 500 руб.\"]"));
    $this->open("/shops/bills/");
    $this->assertTrue($this->isElementPresent("//td[@class=\"col-marker td-left\"][text()=\"" . $tag2 . "\"]"));
    $this->click("css=span.in.cw110");
    sleep(0.5);
    $this->click("name=col-marker");
    $this->click("//input[@value='Применить']");
    // ЗАЧИСТКА
    print("ЗАЧИСТКА" . "\n");
    // Удаляю созданные продукты
    print("Начинаю удаление созданных продуктов" . "\n");
    $this->open("/shops/goods/");
    print("Открываю ищу цифровой продукт и удаляю его" . "\n");
    $this->click("//span[@class=\"in cw110\"]");
    $this->type("//input[@name=\"filter[kw]\"]", $cifr);
    sleep(3);
    $this->click("//a[@class=\"new-button find-item\"]");
    sleep(3);
    $this->click("//i[@class=\"icon-clear\"]");
    $this->assertTrue((bool)preg_match('/^Вы хотите удалить этот объект[\s\S]$/',$this->getConfirmation()));
    sleep(3);
    print("Открываю ищу физический продукт и удаляю его" . "\n");
    $this->click("//span[@class=\"in cw110\"]");
    $this->type("//input[@name=\"filter[kw]\"]", $fiz);
    sleep(3);
    $this->click("//a[@class=\"new-button find-item\"]");
    sleep(3);
    $this->click("//i[@class=\"icon-clear\"]");
    $this->assertTrue((bool)preg_match('/^Вы хотите удалить этот объект[\s\S]$/',$this->getConfirmation()));
    sleep(3);
    print("Открываю ищу плав продукт и удаляю его" . "\n");
    $this->click("//span[@class=\"in cw110\"]");
    $this->type("//input[@name=\"filter[kw]\"]", $plav);
    sleep(3);
    $this->click("//a[@class=\"new-button find-item\"]");
    sleep(3);
    $this->click("//i[@class=\"icon-clear\"]");
    $this->assertTrue((bool)preg_match('/^Вы хотите удалить этот объект[\s\S]$/',$this->getConfirmation()));
    sleep(3);
    $this->click("//span[@class=\"in cw110\"]");
    $this->click("//a[@class=\"new-button find-item\"][@name=\"clear\"]");
    print("Созданные продукты удалены" . "\n");
    // Удаляю созданные категории продуктов
    print("Начинаю удаление созданных категорий продуктов" . "\n");
    $this->click("link=Категории");
    $this->waitForPageToLoad("30000");
    sleep(3);
    print("Открываю фильтр ищу категорию цифр продукта" . "\n");
    $this->click("//span[@class=\"in cw110\"]");
    $this->type("//input[@name=\"filter[kw]\"]", $cifr);
    $this->click("//a[@class=\"new-button find-item\"]");
    sleep(3);
    $this->click("//i[@class=\"icon-clear\"]");
    $this->assertTrue((bool)preg_match('/^Вы хотите удалить этот объект[\s\S]$/',$this->getConfirmation()));
    sleep(3);
    print("Открываю фильтр и  ищу  категорию физ продукта" . "\n");
    $this->click("//span[@class=\"in cw110\"]");
    $this->type("//input[@name=\"filter[kw]\"]", $fiz);
    $this->click("//a[@class=\"new-button find-item\"]");
    sleep(3);
    $this->click("//i[@class=\"icon-clear\"]");
    $this->assertTrue((bool)preg_match('/^Вы хотите удалить этот объект[\s\S]$/',$this->getConfirmation()));
    sleep(3);
    print("Открываю ищу катег плав продукта" . "\n");
    $this->click("//span[@class=\"in cw110\"]");
    $this->type("//input[@name=\"filter[kw]\"]", $plav);
    $this->click("//a[@class=\"new-button find-item\"]");
    sleep(3);
    $this->click("//i[@class=\"icon-clear\"]");
    $this->assertTrue((bool)preg_match('/^Вы хотите удалить этот объект[\s\S]$/',$this->getConfirmation()));
    sleep(3);
    $this->click("//span[@class=\"in cw110\"]");
    $this->click("//a[@class=\"new-button find-item\"][@name=\"clear\"]");
    print("Созданные категориюю удалены" . "\n");
    // Удалаяю созданные группы
    print("Начинаю удаление созданных клиентских групп" . "\n");
    $this->click("link=Группы контактов");
    $this->waitForPageToLoad("30000");
    print("Открываю и ищу клиентскую группу цифрового продукта" . "\n");
    $this->click("//span[@class=\"in cw110\"]");
    $this->type("//input[@name=\"filter[kw]\"]", $cifr);
    $this->click("//a[@class=\"new-button find-item\"]");
    sleep(3);
    $this->click("//i[@class=\"icon-clear\"]");
    $this->assertTrue((bool)preg_match('/^Вы хотите удалить этот объект[\s\S]$/',$this->getConfirmation()));
    sleep(3);
    print("Открываю фильтр и ищу клиентскую группу физ продукта" . "\n");
    $this->click("//span[@class=\"in cw110\"]");
    $this->type("//input[@name=\"filter[kw]\"]", $fiz);
    $this->click("//a[@class=\"new-button find-item\"]");
    sleep(3);
    $this->click("//i[@class=\"icon-clear\"]");
    $this->assertTrue((bool)preg_match('/^Вы хотите удалить этот объект[\s\S]$/',$this->getConfirmation()));
    sleep(3);
    print("Открываю фильтр и ищу клиентскую группу плав продукта" . "\n");
    $this->click("//span[@class=\"in cw110\"]");
    $this->type("//input[@name=\"filter[kw]\"]", $plav);
    $this->click("//a[@class=\"new-button find-item\"]");
    sleep(3);
    $this->click("//i[@class=\"icon-clear\"]");
    $this->assertTrue((bool)preg_match('/^Вы хотите удалить этот объект[\s\S]$/',$this->getConfirmation()));
    sleep(3);
    $this->click("//span[@class=\"in cw110\"]");
    $this->click("//a[@class=\"new-button find-item\"][@name=\"clear\"]");
    print("Созданные группы удалены" . "\n");
    // Удаляю созданные страницы
    print("Начинаю удаление созданных страниц" . "\n");
    $this->click("link=Страницы");
    $this->waitForPageToLoad("30000");
	sleep(5);
    $this->click("link=Основной сайт");
    $this->waitForPageToLoad("30000");
    sleep(5);
    $this->click("css=span.in.cw110");
    $this->type("//input[@name=\"filter[kw]\"]", $testpage);
    $this->click("//a[@class=\"new-button find-item\"]");
    sleep(3);
    $this->click("//i[@class=\"icon-clear\"]");
    $this->assertTrue((bool)preg_match('/^Вы хотите удалить этот объект[\s\S]$/',$this->getConfirmation()));
    sleep(3);
    $this->click("css=span.in.cw110");
    $this->type("//input[@name=\"filter[kw]\"]", $testpage2);
    $this->click("//a[@class=\"new-button find-item\"]");
    sleep(3);
    $this->click("//i[@class=\"icon-clear\"]");
    $this->assertTrue((bool)preg_match('/^Вы хотите удалить этот объект[\s\S]$/',$this->getConfirmation()));
    sleep(3);
    $this->click("//span[@class=\"in cw110\"]");
    $this->click("//a[@class=\"new-button find-item\"][@name=\"no-all-clear\"]");
    print("Созданная страница удалена" . "\n");
    print("Зачистка окончена" . "\n");
    // Удаляю созданную скидку
    $this->open("/shops/discount/");
    // Конец ЗАЧИСТКЕ
	//---------------------------------------------------------
  }
}
?>